<template>
  <div>
    <h1>
      ABCASDJLKASJDLKsaLJKLSAJDLKSJALKABCASDJLKASJDLKsaLJKLSAJDLKSJALKABCASDJLKASJDLKsaLJKLSAJDLKSJALKABCASDJLKASJDLKsaLJKLSAJDLKSJALKDABCASDJLKASJDLKsaLJKLSAJDLKSJALKABCASDJLKASJDLKsaLJKLSAJDLKSJALKABCASDJLKASJDLKsaLJKLSAJDLKSJALKABCASDJLKASJDLKsaLJKLSAJDLKSJALKDABCASDJLKASJDLKsaLJKLSAJDLKSJALKABCASDJLKASJDLKsaLJKLSAJDLKSJALKABCASDJLKASJDLKsaLJKLSAJDLKSJALKABCASDJLKASJDLKsaLJKLSAJDLKSJALKDABCASDJLKASJDLKsaLJKLSAJDLKSJALKABCASDJLKASJDLKsaLJKLSAJDLKSJALKABCASDJLKASJDLKsaLJKLSAJDLKSJALKABCASDJLKASJDLKsaLJKLSAJDLKSJALKD
    </h1>
  </div>
</template>

<style scoped>
div {
  float: right;
  width: 85%;
  overflow-x: hidden;
  word-break: break-all;
  padding: 1%;
}
</style>